/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Xinyiii (https://sketchfab.com/Xinyiii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dell-laptop-1190bd8ffa3247698245fd5e3b4031e6
Title: Dell Laptop
*/

import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export default function ProjectLaptop(props) {
  const groupRef = useRef(null);
  const { nodes, materials } = useGLTF("/models/dell_laptop.glb");
  const txt = useVideoTexture(
    props.video ? props.video : "/textures/project/sample_video.mov"
  );

  useGSAP(() => {
    gsap.from(groupRef.current.rotation, {
      y: Math.PI / 2,
      duration: 1,
      ease: "power3.out",
    });
  }, [props.next]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group
        name="Cube006_8"
        position={[0.292, 0.361, -0.505]}
        rotation={[0, 0, -2.95]}
        scale={[-0.178, 0.105, 1.669]}
      >
        <mesh
          name="Object_14"
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Material}
        />
        <mesh
          name="Object_15"
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          name="Object_16"
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials["Material.025"]}
        />
      </group>
      <group
        name="screen007_204"
        position={[1.253, 0.406, -0.552]}
        rotation={[0, 0, 2.897]}
        scale={[-0.067, 0.066, 0.144]}
      >
        <mesh
          name="Object_358"
          castShadow
          receiveShadow
          geometry={nodes.Object_358.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Object_359"
          castShadow
          receiveShadow
          geometry={nodes.Object_359.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          name="Object_360"
          castShadow
          receiveShadow
          geometry={nodes.Object_360.geometry}
          material={materials.dell_logo2edited}
        />
        <mesh
          name="Object_361"
          castShadow
          receiveShadow
          geometry={nodes.Object_361.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Object_362"
          castShadow
          receiveShadow
          geometry={nodes.Object_362.geometry}
          material={materials.delllogo3}
        />
      </group>
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["8th_gen_core_i5_logo"]}
        position={[-0.576, 0.439, 0.642]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.132}
      />
      <mesh
        name="Object_6"
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials["Material.003"]}
        position={[1.101, 0.395, -2]}
        scale={[0.069, 0.008, 0.099]}
      />
      <mesh
        name="Object_8"
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials["Material.008"]}
        position={[0.898, 0.396, -1.992]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.042, 0.014, 0.016]}
      />
      <mesh
        name="Object_10"
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials["Material.011"]}
        position={[0.577, 0.389, -1.977]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.264, 0.182, 0.041]}
      />
      <mesh
        name="Object_12"
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials["Material.005"]}
        position={[0.897, 0.401, -1.967]}
        scale={[0.039, 0.004, 0.039]}
      />
      <mesh
        name="Object_18"
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials["Material.004"]}
        position={[0.074, 0.378, -1.964]}
        rotation={[0.002, 0, -2.943]}
        scale={[-0.164, 0.105, 1.623]}
      />
      <mesh
        name="Object_20"
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.Material}
        position={[1.053, 0.391, 0.8]}
        rotation={[0, 0, -2.95]}
        scale={[-0.176, 0.083, 1.623]}
      />
      <mesh
        name="Object_22"
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -1.752]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_24"
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials["Material.011"]}
        position={[-0.38, 0.389, -1.931]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.305, 0.182, 0.025]}
      />
      <mesh
        name="Object_26"
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -1.586]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_28"
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -1.415]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_30"
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -1.248]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_32"
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -1.083]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_34"
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.915]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_36"
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.749]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_38"
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.585]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_40"
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.419]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_42"
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.253]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_44"
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, -0.087]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_46"
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, 0.08]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_48"
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, 0.244]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_50"
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, 0.41]}
        scale={[0.048, 0.112, 0.071]}
      />
      <mesh
        name="Object_52"
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials["Material.007"]}
        position={[1.048, 0.421, 0.572]}
        scale={[0.048, 0.112, 0.075]}
      />
      <mesh
        name="Object_54"
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials["Material.007"]}
        position={[0.181, 0.421, -0.66]}
        scale={[0.072, 0.106, 0.419]}
      />
      <mesh
        name="Object_56"
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -1.75]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_58"
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -1.578]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_60"
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -1.408]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_62"
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -1.24]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_64"
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -1.067]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_66"
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.896]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_68"
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.721]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_70"
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.549]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_72"
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.379]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_74"
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.208]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_76"
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, -0.035]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_78"
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, 0.136]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_80"
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, 0.307]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_82"
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials["Material.007"]}
        position={[0.9, 0.421, 0.528]}
        scale={[0.069, 0.116, 0.119]}
      />
      <mesh
        name="Object_84"
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials["Material.007"]}
        position={[0.714, 0.422, -1.697]}
        scale={[0.07, 0.121, 0.12]}
      />
      <mesh
        name="Object_86"
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials["Material.007"]}
        position={[0.539, 0.421, -1.678]}
        scale={[0.07, 0.129, 0.146]}
      />
      <mesh
        name="Object_88"
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials["Material.007"]}
        position={[0.361, 0.421, -1.638]}
        scale={[0.069, 0.131, 0.185]}
      />
      <mesh
        name="Object_90"
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials["Material.007"]}
        position={[0.179, 0.421, -1.727]}
        scale={[0.067, 0.121, 0.095]}
      />
      <mesh
        name="Object_92"
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -1.481]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_94"
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -1.309]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_96"
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -1.139]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_98"
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.971]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_100"
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.798]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_102"
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.627]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_104"
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.452]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_106"
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.28]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_108"
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, -0.11]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_110"
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, 0.061]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_112"
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, 0.234]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_114"
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, 0.405]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_116"
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials["Material.007"]}
        position={[0.715, 0.422, 0.575]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_118"
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials["Material.007"]}
        position={[0.539, 0.421, 0.524]}
        scale={[0.07, 0.129, 0.121]}
      />
      <mesh
        name="Object_120"
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -1.424]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_122"
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -1.253]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_124"
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -1.082]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_126"
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.914]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_128"
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.742]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_130"
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.57]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_132"
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.395]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_134"
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.224]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_136"
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, -0.053]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_138"
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, 0.118]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_140"
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials["Material.007"]}
        position={[0.538, 0.421, 0.29]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_142"
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials["Material.007"]}
        position={[0.361, 0.421, 0.476]}
        scale={[0.069, 0.131, 0.167]}
      />
      <mesh
        name="Object_144"
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.422, -1.342]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_146"
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.422, -1.171]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_148"
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.422, -1]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_150"
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.422, -0.832]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_152"
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.422, -0.66]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_154"
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.421, -0.488]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_156"
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.421, -0.313]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_158"
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.421, -0.142]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_160"
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.421, 0.028]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_162"
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials["Material.007"]}
        position={[0.36, 0.421, 0.2]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_164"
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials["Material.007"]}
        position={[0.181, 0.421, -1.517]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_166"
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials["Material.007"]}
        position={[0.181, 0.421, -1.343]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_168"
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials["Material.007"]}
        position={[0.181, 0.421, -1.173]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_170"
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials["Material.007"]}
        position={[0.183, 0.421, -0.142]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_172"
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials["Material.007"]}
        position={[0.183, 0.421, 0.028]}
        scale={[0.069, 0.116, 0.073]}
      />
      <mesh
        name="Object_174"
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials["Material.007"]}
        position={[0.205, 0.421, 0.2]}
        scale={[0.044, 0.112, 0.071]}
      />
      <mesh
        name="Object_176"
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials["Material.007"]}
        position={[0.079, 0.421, 0.203]}
        scale={[0.044, 0.112, 0.074]}
      />
      <mesh
        name="Object_178"
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials["Material.007"]}
        position={[0.079, 0.421, 0.385]}
        scale={[0.044, 0.112, 0.074]}
      />
      <mesh
        name="Object_180"
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials["Material.007"]}
        position={[0.079, 0.421, 0.568]}
        scale={[0.044, 0.112, 0.074]}
      />
      <mesh
        name="Object_182"
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials["Material.007"]}
        position={[0.205, 0.421, 0.385]}
        scale={[0.044, 0.112, 0.074]}
      />
      <mesh
        name="Object_184"
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials["Material.007"]}
        position={[0.205, 0.421, 0.569]}
        scale={[0.044, 0.112, 0.071]}
      />
      <mesh
        name="Object_186"
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, 0.291]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_188"
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, 0.118]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_190"
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.053]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_192"
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.223]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_194"
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.395]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_196"
        castShadow
        receiveShadow
        geometry={nodes.Object_196.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.57]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_198"
        castShadow
        receiveShadow
        geometry={nodes.Object_198.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.742]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_200"
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -0.915]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_202"
        castShadow
        receiveShadow
        geometry={nodes.Object_202.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -1.082]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_204"
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -1.252]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_206"
        castShadow
        receiveShadow
        geometry={nodes.Object_206.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -1.425]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_208"
        castShadow
        receiveShadow
        geometry={nodes.Object_208.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -1.342]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_210"
        castShadow
        receiveShadow
        geometry={nodes.Object_210.geometry}
        material={materials["Material.012"]}
        position={[0.18, 0.422, -0.659]}
        scale={[0.065, 0.018, 0.408]}
      />
      <mesh
        name="Object_212"
        castShadow
        receiveShadow
        geometry={nodes.Object_212.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -1.17]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_214"
        castShadow
        receiveShadow
        geometry={nodes.Object_214.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.998]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_216"
        castShadow
        receiveShadow
        geometry={nodes.Object_216.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.831]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_218"
        castShadow
        receiveShadow
        geometry={nodes.Object_218.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.659]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_220"
        castShadow
        receiveShadow
        geometry={nodes.Object_220.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.488]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_222"
        castShadow
        receiveShadow
        geometry={nodes.Object_222.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.314]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_224"
        castShadow
        receiveShadow
        geometry={nodes.Object_224.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -0.142]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_226"
        castShadow
        receiveShadow
        geometry={nodes.Object_226.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, 0.03]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_228"
        castShadow
        receiveShadow
        geometry={nodes.Object_228.geometry}
        material={materials["Material.012"]}
        position={[0.539, 0.422, 0.525]}
        scale={[0.065, 0.018, 0.111]}
      />
      <mesh
        name="Object_230"
        castShadow
        receiveShadow
        geometry={nodes.Object_230.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, 0.2]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_232"
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials["Material.012"]}
        position={[0.363, 0.422, 0.478]}
        scale={[0.065, 0.018, 0.158]}
      />
      <mesh
        name="Object_234"
        castShadow
        receiveShadow
        geometry={nodes.Object_234.geometry}
        material={materials["Material.012"]}
        position={[0.183, 0.422, -0.142]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_236"
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials["Material.012"]}
        position={[0.183, 0.422, 0.031]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_238"
        castShadow
        receiveShadow
        geometry={nodes.Object_238.geometry}
        material={materials["Material.012"]}
        position={[0.205, 0.422, 0.2]}
        scale={[0.04, 0.018, 0.065]}
      />
      <mesh
        name="Object_240"
        castShadow
        receiveShadow
        geometry={nodes.Object_240.geometry}
        material={materials["Material.012"]}
        position={[0.205, 0.422, 0.385]}
        scale={[0.042, 0.018, 0.068]}
      />
      <mesh
        name="Object_242"
        castShadow
        receiveShadow
        geometry={nodes.Object_242.geometry}
        material={materials["Material.012"]}
        position={[0.08, 0.422, 0.385]}
        scale={[0.042, 0.018, 0.068]}
      />
      <mesh
        name="Object_244"
        castShadow
        receiveShadow
        geometry={nodes.Object_244.geometry}
        material={materials["Material.012"]}
        position={[0.08, 0.422, 0.567]}
        scale={[0.042, 0.018, 0.068]}
      />
      <mesh
        name="Object_246"
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials["Material.012"]}
        position={[0.08, 0.422, 0.204]}
        scale={[0.042, 0.018, 0.068]}
      />
      <mesh
        name="Object_248"
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials["Material.012"]}
        position={[0.205, 0.422, 0.57]}
        scale={[0.04, 0.018, 0.065]}
      />
      <mesh
        name="Object_250"
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials["Material.012"]}
        position={[0.179, 0.422, -1.342]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_252"
        castShadow
        receiveShadow
        geometry={nodes.Object_252.geometry}
        material={materials["Material.012"]}
        position={[0.179, 0.422, -1.172]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_254"
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials["Material.012"]}
        position={[0.179, 0.422, -1.518]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_256"
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials["Material.012"]}
        position={[0.179, 0.422, -1.726]}
        scale={[0.065, 0.018, 0.087]}
      />
      <mesh
        name="Object_258"
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials["Material.012"]}
        position={[0.361, 0.422, -1.638]}
        scale={[0.065, 0.018, 0.178]}
      />
      <mesh
        name="Object_260"
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials["Material.012"]}
        position={[0.538, 0.422, -1.68]}
        scale={[0.065, 0.018, 0.139]}
      />
      <mesh
        name="Object_262"
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -1.068]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_264"
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -1.698]}
        scale={[0.065, 0.018, 0.113]}
      />
      <mesh
        name="Object_266"
        castShadow
        receiveShadow
        geometry={nodes.Object_266.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -1.309]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_268"
        castShadow
        receiveShadow
        geometry={nodes.Object_268.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -1.138]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_270"
        castShadow
        receiveShadow
        geometry={nodes.Object_270.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.97]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_272"
        castShadow
        receiveShadow
        geometry={nodes.Object_272.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.797]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_274"
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.625]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_276"
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.452]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_278"
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.28]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_280"
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -0.109]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_282"
        castShadow
        receiveShadow
        geometry={nodes.Object_282.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, 0.062]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_284"
        castShadow
        receiveShadow
        geometry={nodes.Object_284.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, 0.233]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_286"
        castShadow
        receiveShadow
        geometry={nodes.Object_286.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, 0.405]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_288"
        castShadow
        receiveShadow
        geometry={nodes.Object_288.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, 0.576]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_290"
        castShadow
        receiveShadow
        geometry={nodes.Object_290.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.896]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_292"
        castShadow
        receiveShadow
        geometry={nodes.Object_292.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.72]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_294"
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.549]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_296"
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.379]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_298"
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials["Material.012"]}
        position={[0.714, 0.422, -1.48]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_300"
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -1.751]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_302"
        castShadow
        receiveShadow
        geometry={nodes.Object_302.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -1.578]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_304"
        castShadow
        receiveShadow
        geometry={nodes.Object_304.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -1.406]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_306"
        castShadow
        receiveShadow
        geometry={nodes.Object_306.geometry}
        material={materials["Material.012"]}
        position={[0.901, 0.422, -1.239]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_308"
        castShadow
        receiveShadow
        geometry={nodes.Object_308.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.209]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_310"
        castShadow
        receiveShadow
        geometry={nodes.Object_310.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, -0.034]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_312"
        castShadow
        receiveShadow
        geometry={nodes.Object_312.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, 0.137]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_314"
        castShadow
        receiveShadow
        geometry={nodes.Object_314.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, 0.308]}
        scale={[0.065, 0.018, 0.065]}
      />
      <mesh
        name="Object_316"
        castShadow
        receiveShadow
        geometry={nodes.Object_316.geometry}
        material={materials["Material.012"]}
        position={[0.9, 0.422, 0.528]}
        scale={[0.065, 0.018, 0.111]}
      />
      <mesh
        name="Object_318"
        castShadow
        receiveShadow
        geometry={nodes.Object_318.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, 0.246]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_320"
        castShadow
        receiveShadow
        geometry={nodes.Object_320.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, 0.41]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_322"
        castShadow
        receiveShadow
        geometry={nodes.Object_322.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, 0.573]}
        scale={[0.043, 0.018, 0.07]}
      />
      <mesh
        name="Object_324"
        castShadow
        receiveShadow
        geometry={nodes.Object_324.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, 0.081]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_326"
        castShadow
        receiveShadow
        geometry={nodes.Object_326.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.087]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_328"
        castShadow
        receiveShadow
        geometry={nodes.Object_328.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.253]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_330"
        castShadow
        receiveShadow
        geometry={nodes.Object_330.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.417]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_332"
        castShadow
        receiveShadow
        geometry={nodes.Object_332.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.584]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_334"
        castShadow
        receiveShadow
        geometry={nodes.Object_334.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.749]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_336"
        castShadow
        receiveShadow
        geometry={nodes.Object_336.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -0.916]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_338"
        castShadow
        receiveShadow
        geometry={nodes.Object_338.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -1.084]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_340"
        castShadow
        receiveShadow
        geometry={nodes.Object_340.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -1.249]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_342"
        castShadow
        receiveShadow
        geometry={nodes.Object_342.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -1.414]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_344"
        castShadow
        receiveShadow
        geometry={nodes.Object_344.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -1.587]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_346"
        castShadow
        receiveShadow
        geometry={nodes.Object_346.geometry}
        material={materials["Material.012"]}
        position={[1.048, 0.422, -1.752]}
        scale={[0.043, 0.018, 0.065]}
      />
      <mesh
        name="Object_348"
        castShadow
        receiveShadow
        geometry={nodes.Object_348.geometry}
        material={materials["Material.014"]}
        position={[0.196, 0.429, -1.364]}
        scale={0.133}
      />
      <mesh
        name="Object_350"
        castShadow
        receiveShadow
        geometry={nodes.Object_350.geometry}
        material={materials["Material.015"]}
        position={[0.197, 0.43, -1.331]}
        scale={0.133}
      />
      <mesh
        name="Object_352"
        castShadow
        receiveShadow
        geometry={nodes.Object_352.geometry}
        material={materials["Material.016"]}
        position={[0.173, 0.425, -1.333]}
        scale={0.133}
      />
      <mesh
        name="Object_354"
        castShadow
        receiveShadow
        geometry={nodes.Object_354.geometry}
        material={materials["Material.017"]}
        position={[0.175, 0.425, -1.364]}
        scale={0.133}
      />
      <mesh
        name="Object_356"
        castShadow
        receiveShadow
        geometry={nodes.Object_356.geometry}
        material={materials["Material.019"]}
        position={[0.575, 0.441, -1.574]}
        scale={0.004}
      />
      <mesh
        name="Object_364"
        castShadow
        receiveShadow
        geometry={nodes.Object_364.geometry}
        material={materials["Material.020"]}
        position={[0.457, 0.406, -0.656]}
        scale={[0.039, 0.037, 0.039]}
      />
      <mesh
        name="Object_366"
        castShadow
        receiveShadow
        geometry={nodes.Object_366.geometry}
        material={materials["Material.021"]}
        position={[0.208, 0.441, 0.386]}
        scale={0.343}
      />
      <mesh
        name="Object_368"
        castShadow
        receiveShadow
        geometry={nodes.Object_368.geometry}
        material={materials["Material.021"]}
        position={[0.08, 0.441, 0.201]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.343}
      />
      <mesh
        name="Object_370"
        castShadow
        receiveShadow
        geometry={nodes.Object_370.geometry}
        material={materials["Material.021"]}
        position={[0.08, 0.441, 0.569]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.343}
      />
      <mesh
        name="Object_372"
        castShadow
        receiveShadow
        geometry={nodes.Object_372.geometry}
        material={materials["Material.021"]}
        position={[0.079, 0.441, 0.386]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.343}
      />
      <mesh
        name="Object_374"
        castShadow
        receiveShadow
        geometry={nodes.Object_374.geometry}
        material={materials["Material.018"]}
        position={[0.799, 0.4, -2.008]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.084}
      />
      <mesh
        name="Object_376"
        castShadow
        receiveShadow
        geometry={nodes.Object_376.geometry}
        material={materials["Material.018"]}
        position={[0.759, 0.418, 0.914]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.084}
      />
      <mesh
        name="Object_378"
        castShadow
        receiveShadow
        geometry={nodes.Object_378.geometry}
        material={materials.material_0}
        position={[1.001, 0.375, 0.884]}
        scale={[0.031, 0.022, 0.031]}
      />
      <mesh
        name="Object_380"
        castShadow
        receiveShadow
        geometry={nodes.Object_380.geometry}
        material={materials["Material.022"]}
        position={[1, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_382"
        castShadow
        receiveShadow
        geometry={nodes.Object_382.geometry}
        material={materials["Material.011"]}
        position={[1.003, 0.371, 0.863]}
        rotation={[1.658, 0, 0]}
        scale={[0.05, 0.081, 0.025]}
      />
      <mesh
        name="Object_384"
        castShadow
        receiveShadow
        geometry={nodes.Object_384.geometry}
        material={materials["Material.022"]}
        position={[1.005, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_386"
        castShadow
        receiveShadow
        geometry={nodes.Object_386.geometry}
        material={materials["Material.022"]}
        position={[1.009, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_388"
        castShadow
        receiveShadow
        geometry={nodes.Object_388.geometry}
        material={materials["Material.022"]}
        position={[1.014, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_390"
        castShadow
        receiveShadow
        geometry={nodes.Object_390.geometry}
        material={materials["Material.022"]}
        position={[1.018, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_392"
        castShadow
        receiveShadow
        geometry={nodes.Object_392.geometry}
        material={materials["Material.022"]}
        position={[1.022, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_394"
        castShadow
        receiveShadow
        geometry={nodes.Object_394.geometry}
        material={materials["Material.022"]}
        position={[1.027, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_396"
        castShadow
        receiveShadow
        geometry={nodes.Object_396.geometry}
        material={materials["Material.022"]}
        position={[0.996, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_398"
        castShadow
        receiveShadow
        geometry={nodes.Object_398.geometry}
        material={materials["Material.022"]}
        position={[0.992, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_400"
        castShadow
        receiveShadow
        geometry={nodes.Object_400.geometry}
        material={materials["Material.022"]}
        position={[0.987, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_402"
        castShadow
        receiveShadow
        geometry={nodes.Object_402.geometry}
        material={materials["Material.022"]}
        position={[0.983, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_404"
        castShadow
        receiveShadow
        geometry={nodes.Object_404.geometry}
        material={materials["Material.022"]}
        position={[0.979, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_406"
        castShadow
        receiveShadow
        geometry={nodes.Object_406.geometry}
        material={materials["Material.022"]}
        position={[0.975, 0.4, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.01, 0.001, 0.015]}
      />
      <mesh
        name="Object_408"
        castShadow
        receiveShadow
        geometry={nodes.Object_408.geometry}
        material={materials["Material.018"]}
        position={[0.647, 0.418, 0.914]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.084}
      />
      <mesh
        name="Object_410"
        castShadow
        receiveShadow
        geometry={nodes.Object_410.geometry}
        material={materials.material_0}
        position={[0.898, 0.385, 0.884]}
        scale={[0.031, 0.01, 0.031]}
      />
      <mesh
        name="Object_412"
        castShadow
        receiveShadow
        geometry={nodes.Object_412.geometry}
        material={materials["Material.011"]}
        position={[0.843, 0.371, 0.863]}
        rotation={[1.658, 0, 0]}
        scale={[0.253, 0.081, 0.025]}
      />
      <mesh
        name="Object_414"
        castShadow
        receiveShadow
        geometry={nodes.Object_414.geometry}
        material={materials["Material.022"]}
        position={[0.899, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_416"
        castShadow
        receiveShadow
        geometry={nodes.Object_416.geometry}
        material={materials["Material.022"]}
        position={[0.903, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_418"
        castShadow
        receiveShadow
        geometry={nodes.Object_418.geometry}
        material={materials["Material.022"]}
        position={[0.908, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_420"
        castShadow
        receiveShadow
        geometry={nodes.Object_420.geometry}
        material={materials["Material.022"]}
        position={[0.912, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_422"
        castShadow
        receiveShadow
        geometry={nodes.Object_422.geometry}
        material={materials["Material.022"]}
        position={[0.916, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_424"
        castShadow
        receiveShadow
        geometry={nodes.Object_424.geometry}
        material={materials["Material.022"]}
        position={[0.921, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_426"
        castShadow
        receiveShadow
        geometry={nodes.Object_426.geometry}
        material={materials["Material.022"]}
        position={[0.925, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_428"
        castShadow
        receiveShadow
        geometry={nodes.Object_428.geometry}
        material={materials["Material.022"]}
        position={[0.895, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_430"
        castShadow
        receiveShadow
        geometry={nodes.Object_430.geometry}
        material={materials["Material.022"]}
        position={[0.89, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_432"
        castShadow
        receiveShadow
        geometry={nodes.Object_432.geometry}
        material={materials["Material.022"]}
        position={[0.886, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_434"
        castShadow
        receiveShadow
        geometry={nodes.Object_434.geometry}
        material={materials["Material.022"]}
        position={[0.882, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_436"
        castShadow
        receiveShadow
        geometry={nodes.Object_436.geometry}
        material={materials["Material.022"]}
        position={[0.878, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_438"
        castShadow
        receiveShadow
        geometry={nodes.Object_438.geometry}
        material={materials["Material.022"]}
        position={[0.874, 0.393, 0.88]}
        rotation={[0, 0, -1.608]}
        scale={[0.005, 0.001, 0.015]}
      />
      <mesh
        name="Object_440"
        castShadow
        receiveShadow
        geometry={nodes.Object_440.geometry}
        material={materials.material_0}
        position={[0.794, 0.384, 0.884]}
        scale={[0.038, 0.01, 0.031]}
      />
      <mesh
        name="Object_442"
        castShadow
        receiveShadow
        geometry={nodes.Object_442.geometry}
        material={materials.material_0}
        position={[0.68, 0.385, 0.884]}
        scale={[0.038, 0.01, 0.031]}
      />
      <mesh
        name="Object_444"
        castShadow
        receiveShadow
        geometry={nodes.Object_444.geometry}
        material={materials["Material.027"]}
        position={[0.793, 0.39, 0.868]}
        rotation={[0, 0, 3.122]}
        scale={[0.037, 0.003, 0.042]}
      />
      <mesh
        name="Object_446"
        castShadow
        receiveShadow
        geometry={nodes.Object_446.geometry}
        material={materials["Material.005"]}
        position={[0.68, 0.39, 0.868]}
        rotation={[0, 0, 3.122]}
        scale={[0.037, 0.003, 0.042]}
      />
      <mesh
        name="Object_448"
        castShadow
        receiveShadow
        geometry={nodes.Object_448.geometry}
        material={materials["Material.026"]}
        position={[1.506, 1.352, -0.534]}
        rotation={[0, 0, 2.897]}
        scale={[-0.067, 0.066, 0.144]}
      >
        <meshBasicMaterial map={txt} />
      </mesh>
      <mesh
        name="Object_450"
        castShadow
        receiveShadow
        geometry={nodes.Object_450.geometry}
        material={materials["Material.011"]}
        position={[0.292, 0.361, -0.505]}
        rotation={[0, 0, -2.95]}
        scale={[-0.178, 0.105, 1.669]}
      />
      <mesh
        name="Object_452"
        castShadow
        receiveShadow
        geometry={nodes.Object_452.geometry}
        material={materials["Material.011"]}
        position={[0.292, 0.361, -0.505]}
        rotation={[0, 0, -2.95]}
        scale={[-0.178, 0.105, 1.669]}
      />
      <mesh
        name="Object_454"
        castShadow
        receiveShadow
        geometry={nodes.Object_454.geometry}
        material={materials["Material.013"]}
        position={[0.696, 0.441, -1.503]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_456"
        castShadow
        receiveShadow
        geometry={nodes.Object_456.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -1.335]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_458"
        castShadow
        receiveShadow
        geometry={nodes.Object_458.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -1.152]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_460"
        castShadow
        receiveShadow
        geometry={nodes.Object_460.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.985]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_462"
        castShadow
        receiveShadow
        geometry={nodes.Object_462.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.813]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_464"
        castShadow
        receiveShadow
        geometry={nodes.Object_464.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.641]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_466"
        castShadow
        receiveShadow
        geometry={nodes.Object_466.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.468]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_468"
        castShadow
        receiveShadow
        geometry={nodes.Object_468.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.289]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_470"
        castShadow
        receiveShadow
        geometry={nodes.Object_470.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, -0.13]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_472"
        castShadow
        receiveShadow
        geometry={nodes.Object_472.geometry}
        material={materials["Material.013"]}
        position={[0.694, 0.441, 0.042]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        name="Object_474"
        castShadow
        receiveShadow
        geometry={nodes.Object_474.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -1.44]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_476"
        castShadow
        receiveShadow
        geometry={nodes.Object_476.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -1.263]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_478"
        castShadow
        receiveShadow
        geometry={nodes.Object_478.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -1.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_480"
        castShadow
        receiveShadow
        geometry={nodes.Object_480.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -0.927]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_482"
        castShadow
        receiveShadow
        geometry={nodes.Object_482.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.44, -0.764]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_484"
        castShadow
        receiveShadow
        geometry={nodes.Object_484.geometry}
        material={materials["Material.013"]}
        position={[0.527, 0.441, -1.795]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_486"
        castShadow
        receiveShadow
        geometry={nodes.Object_486.geometry}
        material={materials["Material.013"]}
        position={[0.352, 0.441, -1.795]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_488"
        castShadow
        receiveShadow
        geometry={nodes.Object_488.geometry}
        material={materials["Material.013"]}
        position={[0.168, 0.441, -1.795]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_490"
        castShadow
        receiveShadow
        geometry={nodes.Object_490.geometry}
        material={materials["Material.013"]}
        position={[0.168, 0.441, -1.536]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_492"
        castShadow
        receiveShadow
        geometry={nodes.Object_492.geometry}
        material={materials["Material.013"]}
        position={[0.168, 0.441, -1.197]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_494"
        castShadow
        receiveShadow
        geometry={nodes.Object_494.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -0.59]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_496"
        castShadow
        receiveShadow
        geometry={nodes.Object_496.geometry}
        material={materials["Material.013"]}
        position={[0.529, 0.441, -0.402]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.056, 0.056, 0.046]}
      />
      <mesh
        name="Object_498"
        castShadow
        receiveShadow
        geometry={nodes.Object_498.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -0.242]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_500"
        castShadow
        receiveShadow
        geometry={nodes.Object_500.geometry}
        material={materials["Material.013"]}
        position={[0.522, 0.441, -0.068]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_502"
        castShadow
        receiveShadow
        geometry={nodes.Object_502.geometry}
        material={materials["Material.013"]}
        position={[0.707, 0.441, -1.795]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_504"
        castShadow
        receiveShadow
        geometry={nodes.Object_504.geometry}
        material={materials["Material.013"]}
        position={[0.904, 0.441, -1.767]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_506"
        castShadow
        receiveShadow
        geometry={nodes.Object_506.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -0.675]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_508"
        castShadow
        receiveShadow
        geometry={nodes.Object_508.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -0.846]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_510"
        castShadow
        receiveShadow
        geometry={nodes.Object_510.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -1.017]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_512"
        castShadow
        receiveShadow
        geometry={nodes.Object_512.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -1.187]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_514"
        castShadow
        receiveShadow
        geometry={nodes.Object_514.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -1.358]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_516"
        castShadow
        receiveShadow
        geometry={nodes.Object_516.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -0.509]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_518"
        castShadow
        receiveShadow
        geometry={nodes.Object_518.geometry}
        material={materials["Material.013"]}
        position={[0.343, 0.44, -0.335]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.056}
      />
      <mesh
        name="Object_520"
        castShadow
        receiveShadow
        geometry={nodes.Object_520.geometry}
        material={materials["Material.013"]}
        position={[0.367, 0.44, -0.153]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_522"
        castShadow
        receiveShadow
        geometry={nodes.Object_522.geometry}
        material={materials["Material.013"]}
        position={[0.367, 0.44, 0.019]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_524"
        castShadow
        receiveShadow
        geometry={nodes.Object_524.geometry}
        material={materials["Material.013"]}
        position={[0.548, 0.44, 0.111]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_526"
        castShadow
        receiveShadow
        geometry={nodes.Object_526.geometry}
        material={materials["Material.013"]}
        position={[0.168, 0.441, -0.161]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_528"
        castShadow
        receiveShadow
        geometry={nodes.Object_528.geometry}
        material={materials["Material.013"]}
        position={[0.168, 0.44, 0.002]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_530"
        castShadow
        receiveShadow
        geometry={nodes.Object_530.geometry}
        material={materials["Material.013"]}
        position={[0.909, 0.441, -1.584]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_532"
        castShadow
        receiveShadow
        geometry={nodes.Object_532.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -1.424]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_534"
        castShadow
        receiveShadow
        geometry={nodes.Object_534.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -1.417]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_536"
        castShadow
        receiveShadow
        geometry={nodes.Object_536.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.441, -0.425]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_538"
        castShadow
        receiveShadow
        geometry={nodes.Object_538.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.441, -0.256]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_540"
        castShadow
        receiveShadow
        geometry={nodes.Object_540.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.441, -0.085]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_542"
        castShadow
        receiveShadow
        geometry={nodes.Object_542.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.441, 0.083]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_544"
        castShadow
        receiveShadow
        geometry={nodes.Object_544.geometry}
        material={materials["Material.013"]}
        position={[0.729, 0.44, 0.226]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_546"
        castShadow
        receiveShadow
        geometry={nodes.Object_546.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.44, 0.226]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_548"
        castShadow
        receiveShadow
        geometry={nodes.Object_548.geometry}
        material={materials["Material.013"]}
        position={[0.729, 0.44, 0.398]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_550"
        castShadow
        receiveShadow
        geometry={nodes.Object_550.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.44, 0.397]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_552"
        castShadow
        receiveShadow
        geometry={nodes.Object_552.geometry}
        material={materials["Material.013"]}
        position={[0.729, 0.44, 0.569]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_554"
        castShadow
        receiveShadow
        geometry={nodes.Object_554.geometry}
        material={materials["Material.013"]}
        position={[0.671, 0.44, 0.571]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_556"
        castShadow
        receiveShadow
        geometry={nodes.Object_556.geometry}
        material={materials["Material.013"]}
        position={[0.493, 0.441, -0.364]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_558"
        castShadow
        receiveShadow
        geometry={nodes.Object_558.geometry}
        material={materials["Material.013"]}
        position={[0.493, 0.441, -0.193]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_560"
        castShadow
        receiveShadow
        geometry={nodes.Object_560.geometry}
        material={materials["Material.013"]}
        position={[0.493, 0.441, -0.025]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_562"
        castShadow
        receiveShadow
        geometry={nodes.Object_562.geometry}
        material={materials["Material.013"]}
        position={[0.316, 0.441, -0.275]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.035}
      />
      <mesh
        name="Object_564"
        castShadow
        receiveShadow
        geometry={nodes.Object_564.geometry}
        material={materials["Material.013"]}
        position={[0.53, 0.441, 0.512]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_566"
        castShadow
        receiveShadow
        geometry={nodes.Object_566.geometry}
        material={materials["Material.013"]}
        position={[0.356, 0.441, 0.529]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_568"
        castShadow
        receiveShadow
        geometry={nodes.Object_568.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -1.248]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_570"
        castShadow
        receiveShadow
        geometry={nodes.Object_570.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -1.247]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_572"
        castShadow
        receiveShadow
        geometry={nodes.Object_572.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -1.077]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_574"
        castShadow
        receiveShadow
        geometry={nodes.Object_574.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -1.076]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_576"
        castShadow
        receiveShadow
        geometry={nodes.Object_576.geometry}
        material={materials["Material.013"]}
        position={[1.035, 0.441, -1.795]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_578"
        castShadow
        receiveShadow
        geometry={nodes.Object_578.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -0.911]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_580"
        castShadow
        receiveShadow
        geometry={nodes.Object_580.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.905]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_582"
        castShadow
        receiveShadow
        geometry={nodes.Object_582.geometry}
        material={materials["Material.013"]}
        position={[1.056, 0.441, 0.523]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_584"
        castShadow
        receiveShadow
        geometry={nodes.Object_584.geometry}
        material={materials["Material.013"]}
        position={[0.89, 0.441, 0.452]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_586"
        castShadow
        receiveShadow
        geometry={nodes.Object_586.geometry}
        material={materials["Material.013"]}
        position={[0.918, 0.441, 0.13]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_588"
        castShadow
        receiveShadow
        geometry={nodes.Object_588.geometry}
        material={materials["Material.013"]}
        position={[0.908, 0.441, 0.294]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_590"
        castShadow
        receiveShadow
        geometry={nodes.Object_590.geometry}
        material={materials["Material.013"]}
        position={[0.539, 0.44, 0.285]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_592"
        castShadow
        receiveShadow
        geometry={nodes.Object_592.geometry}
        material={materials["Material.013"]}
        position={[0.367, 0.44, 0.191]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_594"
        castShadow
        receiveShadow
        geometry={nodes.Object_594.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.893]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_596"
        castShadow
        receiveShadow
        geometry={nodes.Object_596.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -1.067]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_598"
        castShadow
        receiveShadow
        geometry={nodes.Object_598.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -1.234]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_600"
        castShadow
        receiveShadow
        geometry={nodes.Object_600.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -1.397]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_602"
        castShadow
        receiveShadow
        geometry={nodes.Object_602.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -1.569]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_604"
        castShadow
        receiveShadow
        geometry={nodes.Object_604.geometry}
        material={materials["Material.013"]}
        position={[1.056, 0.441, 0.365]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_606"
        castShadow
        receiveShadow
        geometry={nodes.Object_606.geometry}
        material={materials["Material.013"]}
        position={[1.056, 0.441, 0.215]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_608"
        castShadow
        receiveShadow
        geometry={nodes.Object_608.geometry}
        material={materials["Material.013"]}
        position={[1.056, 0.441, 0.037]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_610"
        castShadow
        receiveShadow
        geometry={nodes.Object_610.geometry}
        material={materials["Material.013"]}
        position={[1.056, 0.441, -0.131]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_612"
        castShadow
        receiveShadow
        geometry={nodes.Object_612.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.733]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_614"
        castShadow
        receiveShadow
        geometry={nodes.Object_614.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.569]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_616"
        castShadow
        receiveShadow
        geometry={nodes.Object_616.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.405]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_618"
        castShadow
        receiveShadow
        geometry={nodes.Object_618.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.238]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_620"
        castShadow
        receiveShadow
        geometry={nodes.Object_620.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, -0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_622"
        castShadow
        receiveShadow
        geometry={nodes.Object_622.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, 0.079]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_624"
        castShadow
        receiveShadow
        geometry={nodes.Object_624.geometry}
        material={materials["Material.013"]}
        position={[1.018, 0.441, 0.236]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.036}
      />
      <mesh
        name="Object_626"
        castShadow
        receiveShadow
        geometry={nodes.Object_626.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -0.73]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_628"
        castShadow
        receiveShadow
        geometry={nodes.Object_628.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.732]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_630"
        castShadow
        receiveShadow
        geometry={nodes.Object_630.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -0.565]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_632"
        castShadow
        receiveShadow
        geometry={nodes.Object_632.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.562]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_634"
        castShadow
        receiveShadow
        geometry={nodes.Object_634.geometry}
        material={materials["Material.013"]}
        position={[0.919, 0.441, -0.39]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.042}
      />
      <mesh
        name="Object_636"
        castShadow
        receiveShadow
        geometry={nodes.Object_636.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.393]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_638"
        castShadow
        receiveShadow
        geometry={nodes.Object_638.geometry}
        material={materials["Material.013"]}
        position={[0.928, 0.441, -0.222]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.042, 0.042, 0.035]}
      />
      <mesh
        name="Object_640"
        castShadow
        receiveShadow
        geometry={nodes.Object_640.geometry}
        material={materials["Material.013"]}
        position={[0.943, 0.441, -0.028]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.042, 0.042, 0.035]}
      />
      <mesh
        name="Object_642"
        castShadow
        receiveShadow
        geometry={nodes.Object_642.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.224]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_644"
        castShadow
        receiveShadow
        geometry={nodes.Object_644.geometry}
        material={materials["Material.013"]}
        position={[0.863, 0.441, -0.049]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.048}
      />
      <mesh
        name="Object_646"
        castShadow
        receiveShadow
        geometry={nodes.Object_646.geometry}
        material={materials["Material.013"]}
        position={[0.216, 0.44, 0.163]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_648"
        castShadow
        receiveShadow
        geometry={nodes.Object_648.geometry}
        material={materials["Material.013"]}
        position={[0.216, 0.441, 0.532]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_650"
        castShadow
        receiveShadow
        geometry={nodes.Object_650.geometry}
        material={materials["Material.013"]}
        position={[0.179, 0.441, 0.524]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.04}
      />
      <mesh
        name="Object_652"
        castShadow
        receiveShadow
        geometry={nodes.Object_652.geometry}
        material={materials.material_0}
        position={[0.884, 0.403, 0.915]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.011}
      />
    </group>
  );
}

useGLTF.preload("/models/dell_laptop.glb");
